name: Deploy Bicep file
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./GithubAction.bicep
        parameters: 'storagePrefix=chrisaction storageSKU=Standard_LRS'
        failOnStdErr: false

    - name: Get the most recent deployment name
      id: get-deployment-name
      run: |
        DEPLOYMENT_NAME=$(az deployment group list \
          --resource-group ${{ secrets.AZURE_RG }} \
          --query "[0].name" -o tsv)
        echo "Deployment Name: $DEPLOYMENT_NAME"
        echo "DEPLOYMENT_NAME=$DEPLOYMENT_NAME" >> $GITHUB_ENV

    - name: Retrieve deployment outputs
      run: |
        az deployment group show \
          --resource-group ${{ secrets.AZURE_RG }} \
          --name ${{ env.DEPLOYMENT_NAME }} \
          --query properties.outputs > outputs.json

    - name: Display deployment outputs
      run: |
        echo "Deployment Outputs:"
        cat outputs.json
        
    - name: Save output to artifact
      uses: actions/upload-artifact@v3
      with:
        name: deployment-output
        path: outputs.json
